config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'

  resources :states do
    get '/cities/', to: 'cities#index'
    get '/cities/:slug', to: 'cities#show'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-BR" dir="ltr">
  <head>
    <title>COVID-19 Brasil</title>
    <meta charset="utf-8">
    <meta http-equiv="Content-Language" content="pt-br">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag "corona.png" %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" >
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500" rel="stylesheet">
    <link href="https://unpkg.com/material-components-web@v4.0.0/dist/material-components-web.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"/>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <script src="https://unpkg.com/material-components-web@v4.0.0/dist/material-components-web.min.js"></script>
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
  </head>

  <body class="mdc-typography">
    <div id="container" class="mdc-layout-grid">
      <div class="mdc-layout-grid__inner">
        <div class="mdc-layout-grid__cell bottom mdc-layout-grid__cell--span-3 mdc-layout-grid__cell--span-12-phone sidebar">
          <h1 class="mdc-typography--headline3"><a href="/">COVID-19 Brasil</a></h1>
          <% if @brazil %>
          <hr/>

          <h2 class="mdc-typography--headline4">Total de casos confirmados</h2>

          <span class="total-confirmed"><%= number_with_delimiter(@brazil.confirmed, delimiter: '.') %></span>

          <h3 class="mdc-typography--headline5">Total de mortes: <%= number_with_delimiter(@brazil.deaths, delimiter: '.') %></h3>

          <h3 class="mdc-typography--headline5">Casos recuperados: <%= number_with_delimiter(@brazil.recovered, delimiter: '.') %></h3>
          <% end %>
          <span class="mdc-typography--caption">
            Fonte: <a href="https://covid19-brazil-api.now.sh/" target="_blank">Covid19 Brazil API</a>
          </span>

          <hr />

          <ul class="mdc-list">
            <% @states.each do |state| %>
              <li class="mdc-list-item">
                <%= link_to state_cities_path(state.uf.downcase) do %>
                  <%= state.name %>
                  <span class='mdc-list-item__meta'><%= number_with_delimiter(state.cases, delimiter: '.') %></span>
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
        <div class="main-content top mdc-layout-grid__cell mdc-layout-grid__cell--span-9-desktop mdc-layout-grid__cell--span-12-phone">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'main', 'data-turbolinks-track': 'reload' %>
  <%= yield :javascript %>
</html>